# Name of the workflow
name: Node.js CI

# Specifies the events that trigger the workflow. In this case, it triggers on a push to the main branch and on pull requests targeting the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Defines the job(s) that will be executed.
jobs:
  build:
    # Specifies the type of runner (virtual machine) to use. In this example, it uses the latest Ubuntu environment.
    runs-on: ubuntu-latest

    # Contains the sequence of steps to execute.
    steps:
      # This action checks out your repository so the workflow can access the code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sets up Node.js, if needed (this step can be removed if not necessary).
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version

      #  Installs the dependencies listed in package.json
      - name: Install dependencies
        run: npm install

      - name: lodash
        run: npm install lodash@4.17.21

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit: update generated files"

      - name: Commit changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: $PAT_TOKEN
